#!/bin/bash

read -r -p "enter how many numbers you want average of: " N

sum=0

for ((i=1; i<=$N; i++))
do
	read -r -p "Now enter the numbers: " num
	sum=$(($sum + $num))
done
echo "togal sum is " $sum

avg=$(echo $sum / $N | bc -l)

echo $avg

#printf '%0.2f' "avg"

