#!/bin/bash

echo "how many numbers you want to check"
read N

i=1
max=0

echo " Now enter the Numbers: "

while [ $i -le $N ]
do
	read num
	if [ $i -eq 1 ]		# set first number as max
	then
		max=$num
	else			# from number 2 update max if the num > max.
		if [ $num -gt $max ]
		then
		max=$num
		fi
	fi
	i=$((i+1))		# increment i by 1
done

echo "greatest number is: " $max
	
